# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vasavi_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
