# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasavi_rates', '0004_auto_20171026_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
