# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasavi_rates', '0005_auto_20171027_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bag_weight',
            field=models.IntegerField(default=0),
        ),
    ]
